name: Sync With AZDO

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SyncWithAZDO:
    # The type of runner that the job will run on
    name: SyncWithAZDO
    runs-on: [windows-2019]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{ github.repository }}
          ref: main

      - name: change remote origin url
        run: git remote set-url origin https://${{ secrets.AZDO_LVCICD_PAT_TOKEN }}@dev.azure.com/ni/GlobalSupport/_git/lvCICD

      - name: Show Git remote
        run: git remote -v

      - name: show Git branch
        run: git branch

      - name: config user.email
        run: git config --global user.email "yao.li@ni.com"

      - name: config Main user.name
        run: git config --global user.name "SyncWithAZDO.yml"

      - name: allow shallowupdate
        run: git config receive.shallowupdate true

      - name: push fetch main from AZDO
        run: git fetch origin

      - name: push main branch to AZDO
        run: git push -f --tags --progress origin main:main
